### ISSUE TITLE
Pressure is always 1048576.0

### ISSUE THREAD

**Issue by jwillikers** [copterust/bmp280#4]
Any idea why I would be getting `1048576.0` as the value for pressure every time? I reset the config to forced each time like in the example in the proving ground repository. I'm using the latest commit from master.

**Comment by little-arhat** [comment]
Hello! Could you please try smth like this https://github.com/copterust/proving-ground/blob/master/bmp280/main.rs? 

Also, what does temp senso read?

**Comment by jwillikers** [comment]
You know what, I think the problem is the I2C address. I was able to get readings using the `bmp280-rs` library by using `0x77` as the address instead of `0x76`, which I notice is hard-coded here.

**Comment by bofh** [comment]
Documentation mentions SDO pin that selects 0x77 or 0x76 address, even on the fly.

**Comment by jwillikers** [comment]
I should probably give that a try. I got the Adafruit dev-board for the BMP280 to avoid soldering, since why solder if I can avoid it. I bet I can probe the SDO pinout with a pogo pin or something and see if that works. Thanks for the tip.

**Comment by jwillikers** [comment]
I went ahead and tested against my fork where I just changed `0x76` to `0x77` and that gets me actual pressure values printing, no fixed value.  It'd be nice to be able to set the I2C address in software. I'd be willing to submit a PR if you'd like.

**Comment by little-arhat** [comment]
closed by #5

**Comment by jlpettersson** [comment]
I get the same problem. And temperature is always 0.0.

I have tried with both address 0x76 and 0x77.
