### ISSUE TITLE
Documentation link in README is wrong

### ISSUE THREAD

**Issue by Jajcus** [copterust/bmp280#6]
It seems that ``README.md`` points to API documentation for a completely different 'bmp280' module. This is very confusing.

Actual API documentation would be very helpful, but at least the wrong link should be removed.

**Comment by little-arhat** [comment]
@Jajcus oops, thanks! fixed! Correct name in docs/crates is docs.rs/bmp280-ehal/ (bmp280 was taken by non-embedded-hal compatible crate).
